services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    env_file: .env
    ports: ["127.0.0.1:3000:3000"]
    depends_on:
      db:
        condition: service_healthy
